#!/usr/bin/env python3
"""
cluster.py — Semantic pre-clustering of raw documents before compilation.

Groups raw documents into topically coherent clusters of 15-25 docs using
TF-IDF + cosine similarity + agglomerative clustering. Outputs a cluster
manifest that the compile phase uses to batch work and enable cross-doc
synthesis within each cluster.

Usage:
    python scripts/cluster.py [--kb-root .] [--min-size 10] [--max-size 25] [--output clusters.json]

Output (clusters.json):
    {
      "generated": "2025-05-02T15:00:00Z",
      "clusters": [
        {
          "id": "cluster-001",
          "label": "<auto-generated topic label>",
          "docs": ["raw/articles/foo.md", "raw/articles/bar.md", ...],
          "size": 18,
          "coherence_score": 0.72
        },
        ...
      ],
      "unclustered": ["raw/articles/outlier.md"]
    }

Algorithm:
  1. Read all pending raw docs (not yet in _summaries.md)
  2. Extract text, compute TF-IDF vectors
  3. Agglomerative clustering with ward linkage, distance threshold auto-tuned
     to target cluster sizes in [min_size, max_size]
  4. Label each cluster by top 3 TF-IDF terms
  5. Write cluster manifest to scripts/clusters.json (or specified path)

Dependencies (stdlib + scikit-learn if available, falls back to naive approach):
  - If scikit-learn available: proper TF-IDF + AgglomerativeClustering
  - Fallback: keyword overlap grouping (no external deps)
"""
import argparse
import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ── config ────────────────────────────────────────────────────────────────────

SUPPORTED_EXTENSIONS = {
    ".md", ".txt", ".html", ".htm", ".pdf",
    ".png", ".jpg", ".jpeg", ".gif", ".svg",
}


def load_config(kb_root: Path) -> dict:
    cfg_path = kb_root / "kb.config.json"
    if cfg_path.exists():
        return json.loads(cfg_path.read_text(encoding="utf-8"))
    return {}


def get_skip_patterns(cfg: dict) -> list[str]:
    return cfg.get("ingest", {}).get("quality_filter", {}).get("skip_patterns", [])


def matches_skip_pattern(name: str, patterns: list[str]) -> bool:
    import fnmatch
    return any(fnmatch.fnmatch(name, pat) for pat in patterns)


# ── document loading ──────────────────────────────────────────────────────────

def load_summarized_names(summaries_path: Path) -> set[str]:
    if not summaries_path.exists():
        return set()
    content = summaries_path.read_text(encoding="utf-8", errors="replace")
    return set(re.findall(r"\*\*([\w\-. ]+\.\w+)\*\*", content))


def list_pending_docs(kb_root: Path, skip_patterns: list[str]) -> list[Path]:
    """Return raw docs not yet compiled (not in _summaries.md)."""
    raw_dir = kb_root / "raw"
    summaries_path = kb_root / "wiki" / "_summaries.md"
    summarized = load_summarized_names(summaries_path)

    docs = []
    if not raw_dir.exists():
        return docs
    for f in raw_dir.rglob("*"):
        if f.is_file() and f.suffix.lower() in SUPPORTED_EXTENSIONS:
            if not matches_skip_pattern(f.name, skip_patterns):
                if f.name not in summarized:
                    docs.append(f)
    return sorted(docs)


def extract_text(filepath: Path, max_chars: int = 5000) -> str:
    """Extract first max_chars of readable text from a file."""
    if filepath.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".svg"}:
        return filepath.stem.replace("-", " ").replace("_", " ")
    try:
        text = filepath.read_text(encoding="utf-8", errors="replace")[:max_chars]
        # Strip frontmatter
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                text = text[end + 4:]
        # Strip markdown formatting for better term extraction
        text = re.sub(r"[#*`\[\]()>]", " ", text)
        text = re.sub(r"\s+", " ", text)
        return text.strip()
    except Exception:
        return filepath.stem.replace("-", " ")


# ── clustering algorithms ─────────────────────────────────────────────────────

def try_sklearn_clustering(docs: list[Path], texts: list[str],
                           min_size: int, max_size: int) -> list[list[int]] | None:
    """Attempt clustering with scikit-learn. Returns None if unavailable."""
    try:
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.cluster import AgglomerativeClustering
        from sklearn.metrics.pairwise import cosine_distances
        import numpy as np
    except ImportError:
        return None

    if len(texts) < min_size:
        return [list(range(len(texts)))]

    # TF-IDF vectorization
    vectorizer = TfidfVectorizer(
        max_features=2000,
        stop_words="english",
        min_df=2,
        max_df=0.85,
        ngram_range=(1, 2),
    )
    try:
        tfidf_matrix = vectorizer.fit_transform(texts)
    except ValueError:
        # Too few documents or all stopwords
        return [list(range(len(texts)))]

    # Compute distance matrix
    dist_matrix = cosine_distances(tfidf_matrix)

    # Binary search for optimal distance_threshold targeting avg cluster size
    target_avg = (min_size + max_size) / 2
    n_docs = len(docs)
    target_n_clusters = max(1, n_docs // int(target_avg))

    best_labels = None
    best_score = float("inf")

    for n_clusters in range(max(1, target_n_clusters - 3),
                            min(n_docs, target_n_clusters + 5)):
        try:
            model = AgglomerativeClustering(
                n_clusters=n_clusters,
                metric="precomputed",
                linkage="average",
            )
            labels = model.fit_predict(dist_matrix)
        except Exception:
            continue

        # Score: how close are cluster sizes to target range?
        cluster_sizes = defaultdict(int)
        for lbl in labels:
            cluster_sizes[lbl] += 1

        penalty = sum(
            max(0, min_size - s) + max(0, s - max_size)
            for s in cluster_sizes.values()
        )
        if penalty < best_score:
            best_score = penalty
            best_labels = labels

    if best_labels is None:
        return [list(range(len(texts)))]

    # Group by label
    clusters: dict[int, list[int]] = defaultdict(list)
    for idx, lbl in enumerate(best_labels):
        clusters[lbl].append(idx)

    return list(clusters.values())


def naive_keyword_clustering(docs: list[Path], texts: list[str],
                             min_size: int, max_size: int) -> list[list[int]]:
    """Fallback clustering using keyword overlap (no external deps)."""
    # Extract top keywords per document
    stop_words = {
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "will", "would", "could",
        "should", "may", "might", "can", "shall", "this", "that", "these",
        "those", "it", "its", "of", "in", "on", "at", "to", "for", "with",
        "by", "from", "as", "into", "through", "during", "before", "after",
        "and", "or", "but", "not", "no", "nor", "if", "then", "than", "so",
        "very", "just", "also", "more", "most", "such", "each", "every",
        "all", "any", "both", "few", "other", "some", "only", "same", "new",
    }

    doc_keywords: list[set[str]] = []
    for text in texts:
        words = re.findall(r"\b[a-z]{3,}\b", text.lower())
        keywords = {w for w in words if w not in stop_words}
        # Keep top 30 by frequency
        from collections import Counter
        freq = Counter(w for w in words if w not in stop_words)
        top = {w for w, _ in freq.most_common(30)}
        doc_keywords.append(top)

    # Greedy clustering: assign each doc to existing cluster with highest overlap
    clusters: list[list[int]] = []
    cluster_keywords: list[set[str]] = []

    for idx in range(len(docs)):
        best_cluster = -1
        best_overlap = 0

        for ci, ckw in enumerate(cluster_keywords):
            if len(clusters[ci]) >= max_size:
                continue
            overlap = len(doc_keywords[idx] & ckw)
            if overlap > best_overlap:
                best_overlap = overlap
                best_cluster = ci

        # Require minimum overlap of 3 keywords to join existing cluster
        if best_cluster >= 0 and best_overlap >= 3:
            clusters[best_cluster].append(idx)
            cluster_keywords[best_cluster] |= doc_keywords[idx]
        else:
            clusters.append([idx])
            cluster_keywords.append(doc_keywords[idx].copy())

    # Merge tiny clusters (< min_size) into nearest neighbor
    merged = True
    while merged:
        merged = False
        for i in range(len(clusters)):
            if len(clusters[i]) < min_size and len(clusters[i]) > 0:
                # Find best merge target
                best_j = -1
                best_overlap = 0
                for j in range(len(clusters)):
                    if i == j or len(clusters[j]) == 0:
                        continue
                    if len(clusters[i]) + len(clusters[j]) > max_size:
                        continue
                    overlap = len(cluster_keywords[i] & cluster_keywords[j])
                    if overlap > best_overlap:
                        best_overlap = overlap
                        best_j = j
                if best_j >= 0:
                    clusters[best_j].extend(clusters[i])
                    cluster_keywords[best_j] |= cluster_keywords[i]
                    clusters[i] = []
                    cluster_keywords[i] = set()
                    merged = True

    return [c for c in clusters if len(c) > 0]


def label_cluster(texts: list[str], indices: list[int]) -> str:
    """Generate a label for a cluster from top terms."""
    from collections import Counter
    stop_words = {
        "the", "a", "an", "is", "are", "was", "were", "be", "have", "has",
        "had", "do", "does", "this", "that", "it", "of", "in", "on", "at",
        "to", "for", "with", "by", "from", "as", "and", "or", "but", "not",
    }
    words = []
    for idx in indices:
        words.extend(re.findall(r"\b[a-z]{4,}\b", texts[idx].lower()))
    freq = Counter(w for w in words if w not in stop_words)
    top = [w for w, _ in freq.most_common(3)]
    return " / ".join(top) if top else "misc"


def compute_coherence(texts: list[str], indices: list[int]) -> float:
    """Naive coherence: average pairwise keyword overlap ratio."""
    if len(indices) < 2:
        return 1.0
    from collections import Counter
    stop_words = {"the", "a", "an", "is", "are", "was", "of", "in", "to", "for", "and", "or"}

    doc_sets = []
    for idx in indices:
        words = set(re.findall(r"\b[a-z]{4,}\b", texts[idx].lower())) - stop_words
        doc_sets.append(words)

    overlaps = []
    sample_size = min(len(indices), 10)  # Sample for large clusters
    import random
    sampled = random.sample(range(len(indices)), sample_size) if len(indices) > 10 else range(len(indices))
    for i in sampled:
        for j in sampled:
            if i >= j:
                continue
            union = doc_sets[i] | doc_sets[j]
            if not union:
                continue
            overlaps.append(len(doc_sets[i] & doc_sets[j]) / len(union))

    return sum(overlaps) / len(overlaps) if overlaps else 0.0


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Cluster raw documents by topic similarity for batch compilation."
    )
    parser.add_argument("--kb-root", default=".", help="Knowledge base root directory")
    parser.add_argument("--min-size", type=int, default=10,
                        help="Minimum cluster size (default: 10)")
    parser.add_argument("--max-size", type=int, default=25,
                        help="Maximum cluster size (default: 25)")
    parser.add_argument("--output", default=None,
                        help="Output file path (default: <kb-root>/scripts/clusters.json)")
    parser.add_argument("--all", action="store_true",
                        help="Cluster ALL raw docs, not just pending ones")
    args = parser.parse_args()

    kb_root = Path(args.kb_root).resolve()
    cfg = load_config(kb_root)
    skip_patterns = get_skip_patterns(cfg)

    # Determine target cluster size from config
    cluster_cfg = cfg.get("compile", {}).get("clustering", {})
    min_size = cluster_cfg.get("min_cluster_size", args.min_size)
    max_size = cluster_cfg.get("max_cluster_size", args.max_size)

    # Get documents to cluster
    if args.all:
        raw_dir = kb_root / "raw"
        docs = sorted(
            f for f in raw_dir.rglob("*")
            if f.is_file() and f.suffix.lower() in SUPPORTED_EXTENSIONS
            and not matches_skip_pattern(f.name, skip_patterns)
        ) if raw_dir.exists() else []
    else:
        docs = list_pending_docs(kb_root, skip_patterns)

    if not docs:
        print("No documents to cluster.")
        sys.exit(0)

    print(f"Clustering {len(docs)} documents (target size: {min_size}-{max_size})...")

    # Extract text from each doc
    texts = [extract_text(d) for d in docs]

    # Try sklearn first, fall back to naive
    cluster_indices = try_sklearn_clustering(docs, texts, min_size, max_size)
    method = "sklearn-tfidf-agglomerative"
    if cluster_indices is None:
        cluster_indices = naive_keyword_clustering(docs, texts, min_size, max_size)
        method = "naive-keyword-overlap"

    print(f"Method: {method}")
    print(f"Clusters formed: {len(cluster_indices)}")

    # Build output manifest
    clusters_out = []
    unclustered = []

    for ci, indices in enumerate(cluster_indices):
        if len(indices) == 1:
            unclustered.append(str(docs[indices[0]].relative_to(kb_root)))
            continue

        cluster_docs = [str(docs[idx].relative_to(kb_root)) for idx in indices]
        label = label_cluster(texts, indices)
        coherence = compute_coherence(texts, indices)

        clusters_out.append({
            "id": f"cluster-{ci + 1:03d}",
            "label": label,
            "docs": cluster_docs,
            "size": len(cluster_docs),
            "coherence_score": round(coherence, 3),
        })

    manifest = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "method": method,
        "total_docs": len(docs),
        "total_clusters": len(clusters_out),
        "config": {
            "min_size": min_size,
            "max_size": max_size,
        },
        "clusters": sorted(clusters_out, key=lambda c: -c["size"]),
        "unclustered": unclustered,
    }

    # Write output
    output_path = Path(args.output) if args.output else kb_root / "scripts" / "clusters.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"\nCluster manifest written to: {output_path}")
    print(f"  Clusters: {len(clusters_out)}")
    print(f"  Unclustered (singletons): {len(unclustered)}")
    print()
    for c in manifest["clusters"][:10]:
        print(f"  {c['id']}: {c['label']} ({c['size']} docs, coherence={c['coherence_score']})")
    if len(manifest["clusters"]) > 10:
        print(f"  ... and {len(manifest['clusters']) - 10} more clusters")


if __name__ == "__main__":
    main()
